resume:
pretrain: 
seed: 1024
data:
    dataset: k400
    modality: video
    num_segments: 8
    seg_length: 1
    batch_size: 16
    num_diff: 5
    workers: 4
    num_classes: 400
    image_tmpl: 'img_{:05d}.jpg'
    train_root: '/your_dataset_path'
    train_list: '/your_dataset_path'
    val_root: '/your_dataset_path'
    val_list: '/your_dataset_path'
    label_list: '/your_dataset_path/sth_labels.csv'
    input_size: 224
    random_shift: True
    num_sample: 2
    rand_aug: False
    rand_erase: False
network:
    arch: ViT-L/14  #ViT-B/32 ViT-B/16
    init: True
    tm: False # localuni t1d atm False
    drop_out: 0.0 
    emb_dropout: 0.0 
    type: clip_k400
    sim_header: None  # Transf   None  
    joint_st: False
    drop_fc: 0     
    n_emb: 512
    side_dim: 512
    fix_clip: False 
    my_fix_clip: True
    sync_bn: False
solver:
    type: cosine
    epochs: 30
    start_epoch: 0
    epoch_offset: 0
    optim: adamw
    lr: 1.e-4
    lr_warmup_step: 4
    weight_decay: 0.15
    loss_type: CE
    evaluate: False
    betas: [0.9, 0.999]
    clip_ratio: 1
    grad_accumulation_steps: 1
    # mixup: True
    smoothing: 0.1
    layer_decay: 1.0 # 0.7
logging:
    print_freq: 10
    eval_freq: 1
    skip_epoch: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
